#!/usr/bin/env bash
# install-launcher.sh - Install (or remove) a `nebuladec` launcher on PATH that
# runs the build for a specific pixi environment, so it can be invoked as plain
# `nebuladec ...` without the `pixi run -e <env> nebuladec ...` prefix.
#
# Invoked by the pixi `install` / `uninstall` tasks, so it runs inside an
# activated pixi environment and reads PIXI_ENVIRONMENT_NAME / PIXI_PROJECT_* /
# PIXI_EXE to learn which environment it targets.
#
# For speed, the launcher sources a cached activation snapshot (the output of
# `pixi shell-hook`) and execs the binary directly, instead of calling
# `pixi run` on every invocation. That avoids pixi's process startup and
# lockfile parse each call (~0.30s -> ~0.12s). The snapshot's `. <activate.d>` /
# overlay lines are evaluated at launch time, so the colcon overlay stays live;
# only the conda environment's PATH/vars are baked, and `install` regenerates
# the snapshot to keep it in sync with the build.

set -euo pipefail

BIN_DIR="${NEBULADEC_BIN_DIR:-${HOME}/.local/bin}"
DATA_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/nebuladec"
LAUNCHER="${BIN_DIR}/nebuladec"

# --- uninstall mode -------------------------------------------------------
if [[ ${1:-} == "--uninstall" ]]; then
    rm -f "${LAUNCHER}"
    rm -rf "${DATA_DIR}"
    echo "[install] removed ${LAUNCHER} and ${DATA_DIR}"
    exit 0
fi

# --- install mode ---------------------------------------------------------
: "${PIXI_ENVIRONMENT_NAME:?must be run via 'pixi run -e <env> install'}"
: "${PIXI_PROJECT_MANIFEST:?missing PIXI_PROJECT_MANIFEST (run via pixi)}"
: "${PIXI_EXE:?missing PIXI_EXE (run via pixi)}"

env_name="${PIXI_ENVIRONMENT_NAME}"
snapshot="${DATA_DIR}/env-${env_name}.sh"

mkdir -p "${BIN_DIR}" "${DATA_DIR}"

# Cache the environment activation. Generate the hook with the active-env
# markers cleared so pixi emits a *pure* activation (PATH/vars + activate.d):
# this task runs inside `pixi run -e <env>`, and from an already-active env pixi
# would otherwise emit a deactivate-then-reactivate sequence that breaks when the
# launcher sources it in a fresh shell. Then drop interactive-only lines a
# launcher does not need: the pixi() shell function and PS1 (everything from the
# trailing "# shellcheck" comment onward) and the bash-completion sourcing.
env -u CONDA_PREFIX -u CONDA_SHLVL -u CONDA_DEFAULT_ENV -u PIXI_IN_SHELL \
    -u PIXI_PROMPT -u PIXI_ENVIRONMENT_NAME \
    "${PIXI_EXE}" shell-hook -e "${env_name}" --manifest-path "${PIXI_PROJECT_MANIFEST}" |
    sed '/bash-completion/d; /^# shellcheck/,$d' >"${snapshot}"

cat >"${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# nebuladec launcher for the '${env_name}' pixi environment.
# Generated by 'pixi run -e ${env_name} install' (scripts/install-launcher.sh).
# Re-run that command to refresh after rebuilding or switching environments.
snapshot="${snapshot}"
if [ -f "\${snapshot}" ]; then
    # shellcheck disable=SC1090
    . "\${snapshot}" >/dev/null 2>&1 || true
    exec nebuladec "\$@"
fi
echo "nebuladec: activation cache \${snapshot} is missing;" >&2
echo "           re-run 'pixi run -e ${env_name} install' (falling back to pixi)." >&2
exec "${PIXI_EXE}" run --frozen --manifest-path "${PIXI_PROJECT_MANIFEST}" -e "${env_name}" nebuladec "\$@"
EOF
chmod +x "${LAUNCHER}"

echo "[install] launcher:        ${LAUNCHER} -> pixi env '${env_name}'"
echo "[install] activation cache: ${snapshot}"
case ":${PATH}:" in
*":${BIN_DIR}:"*) ;;
*) echo "[install] NOTE: ${BIN_DIR} is not on PATH; add: export PATH=\"${BIN_DIR}:\$PATH\"" ;;
esac
